djangoshop/blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('',views.index,name='index'),
    path('<slug:judul>',views.show,name='show'),
    path('kategori/<slug:kategori>',views.kategori,name='kategori'),
]

djangoshop/contact/urls.py
from django.urls import path
from . import views
app_name='contact'
urlpatterns = [
    path('',views.index,name='index')
]

djangoshop/djangoshop/urls.py
from django.contrib import admin
from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static # new
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Contact/',include('contact.urls')),
    path('produk/',include('produk.urls')),
    path('Blog/',include('blog.urls')),
    path('',views.index,name='index')
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoshop/produk/urls.py
from django.urls import path
from . import views
app_name = 'produk'
urlpatterns = [
    path('kategori/<slug:kategori>', views.category,name='category'),
    path('', views.index,name='index'),
    path('<int:kodebarang>', views.show,name='show'),
    
]

djangoshop/blog/models.py
from django.db import models
from django.utils.text import slugify
from kategori_artikel.models import category

class artikel(models.Model):
    judul = models.CharField(max_length=50)
    isi = models.TextField(max_length=1000)
    tanggal = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    slug = models.SlugField(editable=False,blank=True,null=True)
    kategori = models.ForeignKey(category,on_delete=models.SET_NULL, blank=True, null=True)
    gambar = models.ImageField(upload_to='images/')

    def save(self):
        self.slug = slugify(self.judul)
        super(artikel, self).save()

    def __str__(self):
        return self.judul

djangoshop/contact/models.py
from django.db import models

# Create your models here.

djangoshop/kategori_artikel/models.py
from django.db import models
from django.utils.text import slugify

class category(models.Model):
    nama = models.CharField(max_length=50)
    tanggal = models.DateTimeField(auto_now_add=True, blank=True)
    slug = models.SlugField(editable=False,blank=True,null=True)

    def save(self):
        self.slug = slugify(self.nama)
        super(category, self).save()

    def __str__ (self):
        return self.nama

djangoshop/produk/models.py
from django.db import models
from django.utils.text import slugify

class kategori(models.Model):
    nama = models.CharField(max_length=50)
    gambar = models.ImageField(upload_to='images/')
    slug = models.SlugField(editable=False,blank=True,null=True)
    
    def save(self):
        self.slug = slugify(self.nama)
        super(kategori, self).save()

    def __str__(self):
        return self.nama

class barang(models.Model):
    nama = models.CharField(max_length=70)
    deskripsi = models.TextField()
    stok = models.IntegerField()
    diskon = models.IntegerField()
    harga = models.IntegerField()
    kategori = models.ForeignKey(kategori,on_delete=models.SET_NULL,
        blank=True,
        null=True,)
    gambar = models.ImageField(upload_to='images/')
    
    def __str__(self):
        return "%s %s %s" % (self.nama, self.stok, self.harga)

djangoshop/blog/views.py
from django.shortcuts import render
from kategori_artikel.models import category
from . import models

def index(request):
    data_kategori = category.objects.all().order_by('-id')
    data_blog = models.artikel.objects.all().order_by('-id')
    context = {
        'title':'Blog',
        'head':'Halaman Blog',
        'data_kategori':data_kategori,
        'data_blog':data_blog,
    }
    return render(request,'blog/index.html',context)

def show(request,judul):
    data_lain = models.artikel.objects.all().order_by('?')[0:6]
    data_blog = models.artikel.objects.get(slug=judul)
    context = {
        'title':'Blog',
        'data_blog':data_blog,
        'bloglain':data_lain,
    }
    return render(request,'blog/show.html',context)

def kategori(request,kategori):
    data_blog = models.artikel.objects.filter(kategori__slug=kategori)
    data_kategori = category.objects.all().order_by('-id')
    kategori = category.objects.get(slug=kategori)
    context = {
        'title':'Blog',
        'data_blog':data_blog,
        'data_kategori':data_kategori,
        'kategori':kategori,
    }
    print(kategori)
    return render(request,'blog/kategori.html',context)

djangoshop/contact/views.py
from django.shortcuts import render

def index(request):
    context={
        'title':'contact',
    }
    return render(request,'contact/index.html',context)

djangoshop/djangoshop/views.py
from django.shortcuts import render
from produk import models as barang
from blog import models as blogs
from kategori_artikel import models as katar
def index(request):
    Barangs = barang.barang
    KategoriBrg = barang.kategori
    Blogsnya = blogs.artikel
    Kategoriartikel = katar.category

    data_blog = Blogsnya.objects.all().select_related('kategori')
    data_kategori = KategoriBrg.objects.all().order_by('-id')[0:3]
    data_barang = Barangs.objects.all().order_by('-id')[0:8]

    context = {
        'title':'home',
        'head':'home page',
        'kategori':data_kategori,
        'barang':data_barang,
        'blog':data_blog,
    }
    return render(request,'index.html',context)

djangoshop/kategori_artikel/views.py
from django.shortcuts import render

# Create your views here.

djangoshop/produk/views.py
from django.shortcuts import render
from . import models

def index(request):
    data_kategori = models.kategori.objects.all().order_by('-id')
    data_barang = models.barang.objects.all().order_by('-id')
    context = {
        'title':'Produk',
        'head':'Semua Produk',
        'data_kategori':data_kategori,
        'data_barang':data_barang,
    }
    return render(request,'produk/index.html',context)

def show(request, kodebarang):
    data_barang = models.barang.objects.get(id=kodebarang)
    other = models.barang.objects.all().order_by('?')[0:4]
    context={
        'title':'Detail Produk',
        'head':'Detail Produk',
        'barang':data_barang,
        'other_barang':other,
    }
    return render(request,'produk/show.html',context)

def category(request, kategori):
    data_kategori = models.kategori.objects.get(slug=kategori)
    data_barang = models.barang.objects.filter(kategori__slug=kategori).order_by('-id')
    context={
        'title':'Produk',
        'head':'Detail Produk',
        'data_barang':data_barang,
        'kategori':data_kategori,
    }
    return render(request,'produk/category.html',context)

djangoshop/blog/templates/blog/index.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
<title>{{title}}</title>
{% endblock title %}

{% block content %}
<br>
<section class="blog_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog_left_sidebar">
                    {% for rows in data_blog %}
                    <article class="row blog_item">
                       
                        <div class="col-md-12">
                            <div class="blog_post">
                                <img src="{{rows.gambar.url}}" alt="" width="100%">
                                <div class="blog_details">
                                    <a href="single-blog.html">
                                        <h2>{{rows.judul}}</h2>
                                    </a>
                                    <p>{{rows.isi}}</p>
                                    <a class="button button-blog" href="{% url 'blog:show' rows.slug %}">View More</a>
                                </div>
                            </div>
                        </div>
                    </article>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">Kategori</h4>
                        <ul class="list cat-list">
                            {% for row in data_kategori %}
                            <li>
                                <a href="{% url 'blog:kategori' row.slug %}" class="d-flex justify-content-between">
                                    <p>{{row.nama}}</p>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

djangoshop/blog/templates/blog/kategori.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
<title>{{title}}</title>
{% endblock title %}

{% block content %}
<br>
<section class="blog_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                
                <div class="blog_left_sidebar">
                    <h2>Kategori : {{kategori.nama}}</h2>
                    {% for rows in data_blog %}
                    <article class="row blog_item">
                       
                        <div class="col-md-12">
                            <div class="blog_post">
                                <img src="{{rows.gambar.url}}" alt="" width="100%">
                                <div class="blog_details">
                                    <a href="single-blog.html">
                                        <h2>{{rows.judul}}</h2>
                                    </a>
                                    <p>{{rows.isi}}</p>
                                    <a class="button button-blog" href="{% url 'blog:show' rows.slug %}">View More</a>
                                </div>
                            </div>
                        </div>
                    </article>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">Kategori</h4>
                        <ul class="list cat-list">
                            <li>
                                <a href="{% url 'blog:index'%}" class="d-flex justify-content-between">
                                    <p>Semua Kategori</p>
                                </a>
                            </li>
                            {% for row in data_kategori %}
                            <li>
                                <a href="{% url 'blog:kategori' row.slug %}" class="d-flex justify-content-between">
                                    <p>{{row.nama}}</p>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

djangoshop/blog/templates/blog/show.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
<title>{{title}}</title>
{% endblock title %}

{% block content %}
<section class="blog_area single-post-area py-80px section-margin--small">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                <div class="single-post row">
                    <div class="col-lg-12">
                        <div class="feature-img">
                            <img class="img-fluid" src="{{data_blog.gambar.url}}" width="100%">
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 blog_details">
                        <h2>{{data_blog.judul}}</h2>
                        {{data_blog.isi}}
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">Artikel Lain</h3>
                        {% for bl in bloglain %}
                        <div class="media post_item">
                            <img src="{{bl.gambar.url}}" alt="post" style="max-width: 20%;">
                            <div class="media-body">
                                <a href="{% url 'blog:show' bl.slug %}">
                                    <h3>{{bl.judul}}</h3>
                                </a>
                                <p>{{bl.tanggal}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </aside>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

djangoshop/contact/templates/contact/index.html
{% extends 'layout/base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
   <title>{{title}}</title>
{% endblock title %}

{% block content %}
<section class="section-margin--small">
    <div class="container">
      <div class="d-none d-sm-block mb-5 pb-4">
        <div id="map" style="height: 420px;"></div>
        <script>
          function initMap() {
            var uluru = {lat: -25.363, lng: 131.044};
            var grayStyles = [
              {
                featureType: "all",
                stylers: [
                  { saturation: -90 },
                  { lightness: 50 }
                ]
              },
              {elementType: 'labels.text.fill', stylers: [{color: '#A3A3A3'}]}
            ];
            var map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: -31.197, lng: 150.744},
              zoom: 9,
              styles: grayStyles,
              scrollwheel:  false
            });
          }
          
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
        
      </div>


      <div class="row">
        <div class="col-md-4 col-lg-3 mb-4 mb-md-0">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>California United States</h3>
              <p>Santa monica bullevard</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-headphone"></i></span>
            <div class="media-body">
              <h3><a href="tel:454545654">00 (440) 9865 562</a></h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3><a href="mailto:support@colorlib.com">support@colorlib.com</a></h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
        <div class="col-md-8 col-lg-9">
          <form action="#/" class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
            <div class="row">
              <div class="col-lg-5">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" placeholder="Enter your name">
                </div>
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" placeholder="Enter email address">
                </div>
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" placeholder="Enter Subject">
                </div>
              </div>
              <div class="col-lg-7">
                <div class="form-group">
                    <textarea class="form-control different-control w-100" name="message" id="message" cols="30" rows="5" placeholder="Enter Message"></textarea>
                </div>
              </div>
            </div>
            <div class="form-group text-center text-md-right mt-3">
              <button type="submit" class="button button--active button-contactForm">Send Message</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

djangoshop/produk/templates/produk/category.html
{% extends 'layout/base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
<title>{{title}}</title>
{% endblock title %}
{{% block content %}
<section class="section-margin--small mb-5">
  <div class="container">
    <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12">
        <h3>Kategori : {{kategori.nama}}</h3>
<section class="lattest-product-area pb-40 category-list">
  <div class="row">
    {% for rows in data_barang %}
    <div class="col-md-6 col-lg-4">
      <div class="card text-center card-product">
        <div class="card-product__img">
          <img src="{{ rows.gambar.url}}" alt="{{ post.title }}" class="card-img">
          <ul class="card-product__imgOverlay">
            <li><a href="{% url 'produk:show' rows.id %}"><button class="text-white"><i class="ti-eye"></i>
                  Detail</button></a></li>
          </ul>
        </div>
        <div class="card-body">
          <p>{{rows.kategori.nama}}</p>
          <h4 class="card-product__title"><a href="{% url 'produk:show' rows.id %}">{{rows.nama}}</a></h4>
          <p class="card-product__price">Rp. {{rows.harga|intcomma}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
</div>
</div>
</div>
</section>
{% endblock content %}

djangoshop/produk/templates/produk/index.html
{% extends 'layout/base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
<title>{{title}}</title>
{% endblock title %}

{% block content %}
<section class="section-margin--small mb-5">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 col-lg-8 col-md-7">
        <h3>{{head}}</h3>
        <section class="lattest-product-area pb-40 category-list">
          <div class="row">
            {% for rows in data_barang %}
            <div class="col-md-6 col-lg-4">
              <div class="card text-center card-product">
                <div class="card-product__img">
                  <img src="{{ rows.gambar.url}}" alt="{{ post.title }}" class="card-img">
                  <ul class="card-product__imgOverlay">
                    <li><a href="{% url 'produk:show' rows.id %}"><button class="text-white"><i class="ti-eye"></i>
                          Detail</button></a></li>
                  </ul>
                </div>
                <div class="card-body">
                  <p>{{rows.kategori.nama}}</p>
                  <h4 class="card-product__title"><a href="{% url 'produk:show' rows.id %}">{{rows.nama}}</a></h4>
                  <p class="card-product__price">Rp. {{rows.harga|intcomma}}</p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </section>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-5">
        <div class="sidebar-categories">
          <div class="head">Kategori</div>
          <ul class="main-categories">
            <li class="common-filter">
              <ul>
                {% for row in data_kategori %}
                <li class="filter-list"><a href="{% url 'produk:category' row.slug %}"><label
                      for="men">{{row.nama}}</label></a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

djangoshop/produk/templates/produk/show.html
{% extends 'layout/base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
<title>{{title}}</title>
{% endblock title %}

{% block content %}
<div class="product_image_area">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-6">
                <div class="owl-carousel owl-theme s_Product_carousel">
                    <div class="single-prd-item">
                        <img class="img-fluid" src="{{barang.gambar.url}}" alt="">
                    </div>
                    <!-- <div class="single-prd-item">
                        <img class="img-fluid" src="img/category/s-p1.jpg" alt="">
                    </div>
                    <div class="single-prd-item">
                        <img class="img-fluid" src="img/category/s-p1.jpg" alt="">
                    </div> -->
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>{{barang.nama}}</h3>
                    <h2>Rp. {{barang.harga|intcomma}}</h2>
                    <ul class="list">
                        <li><a class="active" href="#"><span>Category</span> : {{barang.kategori.nama}}</a></li>
                        <li><a href="#"><span>Stok</span> : {{barang.stok}} Pcs</a></li>
                    </ul>
                    <p>{{barang.deskripsi}}</p>
                    <br>
                    <div class="product_count">
                        <a class="button primary-btn" href="#">Add to Cart</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br>
<section class="related-product-area section-margin--small mt-0">
    <div class="container">
        <div class="section-intro pb-60px">
            <p>Rekomendasi barang lain</p>
            <h2>Other <span class="section-intro__style">Product</span></h2>
        </div>
        <div class="row mt-30">
            {% for ob in other_barang %}
            <div class="col-sm-6 col-xl-3 mb-4 mb-xl-0">
                <div class="single-search-product-wrapper">
                    <div class="single-search-product d-flex">
                        <a href="{% url 'produk:show' ob.id %}"><img src="{{ob.gambar.url}}" alt=""></a>
                        <div class="desc">
                            <a href="{% url 'produk:show' ob.id %}" class="title">{{ob.nama}}</a>
                            <div class="price">Rp. {{ob.harga|intcomma}}</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

djangoshop/templates/index.html
{% extends 'layout/base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
   <title>{{title}}</title>
{% endblock title %}

{% block content %}
<main class="site-main">
    <section class="hero-banner">
        <div class="container">
            <div class="row no-gutters align-items-center pt-60px">
                <div class="col-5 d-none d-sm-block">
                    <div class="hero-banner__img">
                        <img class="img-fluid" src="{% static 'assets/img/home/hero-banner.png'%}" alt="">
                    </div>
                </div>
                <div class="col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
                    <div class="hero-banner__content">
                        <h1>{{head}}</h1>
                        <p>Us which over of signs divide dominion deep fill bring they're meat beho upon own earth
                            without morning over third. Their male dry. They are great appear whose land fly grass.
                        </p>
                        <a class="button button-hero" href="#">Browse Now</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="section-margin mt-0">
        <div class="owl-carousel owl-theme hero-carousel">
            {% for row in kategori %}
            <div class="hero-carousel__slide">
                <img src="{{row.gambar.url}}" alt="" class="img-fluid">
                <a href="{% url 'produk:category' row.slug %}" class="hero-carousel__slideOverlay">
                    <h3>{{row.nama}}</h3>
                    <p>{{row.nama}} Item</p>
                </a>
            </div>
           {% endfor %}
        </div>
    </section>
    <section class="section-margin calc-60px">
        <div class="container">
            <div class="section-intro pb-60px">
                <p>Barang paling baru di toko kami</p>
                <h2>Fresh <span class="section-intro__style">Product</span></h2>
            </div>
            <div class="row">
                {% for brg in barang %}
                <div class="col-md-6 col-lg-4 col-xl-3">
                    <div class="card text-center card-product">
                        <div class="card-product__img">
                            <img class="card-img" src="{{brg.gambar.url}}" alt="">
                            <ul class="card-product__imgOverlay">
                                <li><a href="{% url 'produk:show' brg.id %}"><button class="text-white"><i class="ti-eye"></i> Detail</button></a></li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <p>{{brg.kategori.nama}}</p>
                            <h4 class="card-product__title"><a href="#">{{brg.nama}}</a></h4>
                            <p class="card-product__price">Rp. {{brg.harga|intcomma}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="offer" id="parallax-1" data-anchor-target="#parallax-1"
        data-300-top="background-position: 20px 30px" data-top-bottom="background-position: 0 20px">
        <div class="container">
            <div class="row">
                <div class="col-xl-5">
                    <div class="offer__content text-center">
                        <h3>Up To 50% Off</h3>
                        <h4>Winter Sale</h4>
                        <p>Him she'd let them sixth saw light</p>
                        <a class="button button--active mt-3 mt-xl-4" href="#">Shop Now</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br><br>
    <section class="blog">
        <div class="container">
            <div class="section-intro">
                <p>Info terbaru dari kami</p>
                <h2>Latest <span class="section-intro__style">Blog</span></h2>
            </div>
            <div class="row">
                {% for blg in blog %}
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                    <div class="card card-blog">
                        <div class="card-blog__img">
                            <img class="card-img rounded-0" src="{{blg.gambar.url}}" alt="">
                        </div>
                        <div class="card-body">
                            <ul class="card-blog__info">
                                <li><a href="#"><i class="ti-tag"></i> {{blg.kategori.nama}}</a></li>
                            </ul>
                            <h4 class="card-blog__title">
                                <a href="{% url 'blog:show' blg.slug %}">{{blg.judul}}</a>
                            </h4>
                            <p>{{blg.isi}}</p>
                            <a class="card-blog__link" href="{% url 'blog:show' blg.slug %}">
                                Read More <i class="ti-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <br><br>
</main>
{% endblock content %}

djangoshop/templates/layout/nav.html
{% load static %}
<header class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand logo_h" href="{% url 'index' %}"><img src="{% static 'assets/img/logo.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
                        <li class="nav-item active"><a class="nav-link" href="{% url 'produk:index'%}">Product</a></li>
                        <li class="nav-item active"><a class="nav-link" href="{% url 'blog:index' %}">Blog</a></li>
                        <li class="nav-item active"><a class="nav-link" href="{% url 'contact:index' %}">Contact</a></li>
                    </ul>

                    
                </div>
            </div>
        </nav>
    </div>
</header>